// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YAMi_API.VeriTabani;

#nullable disable

namespace YAMi_API.Migrations
{
    [DbContext(typeof(YAMiDbContext))]
    [Migration("20250701231051_Düzenleme3")]
    partial class Düzenleme3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YAMi_API.Siniflar.Kozmetik", b =>
                {
                    b.Property<Guid>("KId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("KAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("KAlis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KMiktari")
                        .HasColumnType("int");

                    b.Property<decimal>("KSatisF")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KId");

                    b.ToTable("Kozmetik");
                });

            modelBuilder.Entity("YAMi_API.Siniflar.MeyveVeSebze", b =>
                {
                    b.Property<Guid>("MId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MAlis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MMiktari")
                        .HasColumnType("int");

                    b.Property<decimal>("MSatisF")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MId");

                    b.ToTable("MeyveVeSebze");
                });

            modelBuilder.Entity("YAMi_API.Siniflar.Musteri", b =>
                {
                    b.Property<Guid>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MAdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MKullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MTelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("YAMi_API.Siniflar.Pastane", b =>
                {
                    b.Property<Guid>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("EkleyenPersonel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuncelleyenPersonel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PAlis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PMiktari")
                        .HasColumnType("int");

                    b.Property<decimal>("PSatisF")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PId");

                    b.ToTable("Pastane");
                });

            modelBuilder.Entity("YAMi_API.Siniflar.Personel", b =>
                {
                    b.Property<Guid>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PAdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PKullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonelId");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("YAMi_API.Siniflar.Sepet", b =>
                {
                    b.Property<Guid>("SepetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UrunAdet")
                        .HasColumnType("int");

                    b.Property<Guid>("UrunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrunTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SepetId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Sepet");
                });

            modelBuilder.Entity("YAMi_API.Siniflar.YiyecekVeIcecek", b =>
                {
                    b.Property<Guid>("YId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("YAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("YAlis")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("YMiktari")
                        .HasColumnType("int");

                    b.Property<decimal>("YSatisF")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("YId");

                    b.ToTable("YiyecekVeIcecek");
                });

            modelBuilder.Entity("YAMi_API.Siniflar.Sepet", b =>
                {
                    b.HasOne("YAMi_API.Siniflar.Musteri", "Musteri")
                        .WithMany()
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musteri");
                });
#pragma warning restore 612, 618
        }
    }
}
